---

- name: apply common configuration to all nodes
  hosts:
   - all
  user: root
  roles:
    - common

- hosts: all
  tasks:
    - group_by: key=ansible_system_vendor_{{ ansible_system_vendor }}
      changed_when: False

- hosts: ansible_system_vendor_IBM
  gather_facts: False
  tasks:
     - yum: name=ibm_utl_asu state=present
